### ISSUE TITLE
Code uses panic() instead of returning errors

### ISSUE THREAD

**Issue by asmaloney** [jasonwinn/geocoder#5]
Is there a way to catch invalid API keys?

```panic: invalid character 'T' looking for beginning of value```

**Comment by asmaloney** [comment]
So it looks like any failure results in a panic instead of returning errors properly.

Although it's the only geo solution I've found so far that implements batch geocoding, panics make it less useful...

**Comment by jasonwinn** [comment]
Sorry for the late reply! Unfortunately I haven't been able to give this library any attention. Feel free to issue a pull request and I will happily check it out.

**Comment by cdipaolo** [comment]
I can do this later today or tomorrow. Shouldn't be too hard.

**Comment by cdipaolo** [comment]
Done. See #9

**Comment by jasonwinn** [comment]
Done! #9 is merged.

**Comment by cdipaolo** [comment]
Thanks!

**Comment by asmaloney** [comment]
:+1:
